#ifndef _TIMER2_CONFIG_H_
#define _TIMER2_CONFIG_H_






//#define TIMER0_WAVEFORM_GENERATION_MODE		TIMER_FAST_PWM_MODE
#define TIMER2_CTC_VAL						0
/*Set the Required Prescaler
	 * Choose between
	 * - TIMER_NO_CLOCK_SOURCE
	 * - TIMER_NO_PRESCALER_FACTOR
	 * - TIMER_DIVISION_FACTOR_8
	 * - TIMER_DIVISION_FACTOR_64
	 * - TIMER_DIVISION_FACTOR_256
	 * - TIMER_DIVISION_FACTOR_1024
	
*/
#define TIMER2_PRESCALER		TIMER_DIVISION_FACTOR_8
/*Set PWM Mode
		 * Choose between
		 * 1. TIMER_OC_DISCONNECTED
		 * 2. TIMER_CLR_ON_CTC_SET_ON_TOP
		 * 3. TIMER_SET_ON_CTC_CLR_ON_TOP
 */
#define TIMER2_CTC_PWM_MODE						TIMER_CLR_ON_CTC_SET_ON_TOP
#endif